spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username:
    password: 
server:
  servlet:
    context-path: "/api"
  port: 8080

logging:
  level:
    com:
      ifmo: debug